- name: "feature"
  color: "0e8a16"
  description: "Any new significant addition"
- name: "fix"
  color: "b60205"
  description: "Fixes a bug"
- name: "test"
  color: "c2e0c6"
  description: "Unit tests, mocking, integration testing"
- name: "refactor"
  color: "FFA500"
  description: "Any significant refactoring"
- name: "tested"
  color: "50e061"
  description: "PR was tested by a team member"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "chore"
  color: "006b75"
  description: "Changes not related to production nor test code"
- name: "dependencies"
  color: "006b75"
  description: "Dependency updates"
- name: "work-in-progress"
  color: "FBCA04"
  description: "Used for denoting a WIP"
- name: "build"
  color: "0D2D8C"
  description: "PR was tested by a team member"
- name: "ci"
  color: "54CEE7"
  description: "CI/CD related changes"
- name: "performance"
  color: "F1F53A"
  description: "Changes related to performance"

- name: "idea"
  color: "cccccc"
  description: "Any idea, suggestion or opinion"
- name: "experimental"
  color: "d4c5f9"
  description: "Experimental - can break!"
- name: "question"
  color: "cc317c"
  description: "Any question or concern"
- name: "stale"
  color: "c2e0c6"
  description: "Old, unused, stale"
