- color: "0e8a16"
  description: "Any new significant addition"
  name: "feature"
- color: "b60205"
  description: "Fixes a bug"
  name: "fix"
- color: "c2e0c6"
  description: "Unit tests, mocking, integration testing"
  name: "test"
- color: "FFA500"
  description: "Any significant refactoring"
  name: "refactor"
- color: "50e061"
  description: "PR was tested by a team member"
  name: "tested"
- color: "0075ca"
  description: "Improvements or additions to documentation"
  name: "documentation"
- color: "006b75"
  description: "Changes not related to production nor test code"
  name: "chore"
- color: "006b75"
  description: "Dependency updates"
  name: "dependencies"
- color: "FBCA04"
  description: "Used for denoting a WIP"
  name: "work-in-progress"
- color: "0D2D8C"
  description: "PR was tested by a team member"
  name: "build"
- color: "54CEE7"
  description: "CI/CD related changes"
  name: "ci"
- color: "F1F53A"
  description: "Changes related to performance"
  name: "performance"

- color: "cccccc"
  description: "Any idea, suggestion or opinion"
  name: "idea"
- color: "d4c5f9"
  description: "Experimental - can break!"
  name: "experimental"
- color: "cc317c"
  description: "Any question or concern"
  name: "question"
- color: "c2e0c6"
  description: "Old, unused, stale"
  name: "stale"
