name: Automatic Git Tag
permissions:
  contents: write

on:
  push:
    branches: [master, main]

jobs:
  on-push:
    uses: bactions/workflows/.github/workflows/tag-new-version.yml@go-generate
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
