name: "Test and lint the branch"

on:
  push:
    branches-ignore:
      - main
      - master

permissions:
  contents: write
  pull-requests: read

jobs:
  on-push:
    uses: bactions/workflows/.github/workflows/on-push-go.yml@main
    secrets:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  test-docs:
    name: Test build of docs page
    runs-on: ubuntu-latest
    needs: [on-push]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: docs/package.json
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Build website
        run: yarn build
        working-directory: docs
