name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-lib.yml@main
    with:
      version: ${{ github.ref_name }}

  build_docs:
    name: Build docs page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: docs/package.json
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Build website
        run: yarn deploy
        working-directory: docs
