name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release_default:
    uses: bactions/workflows/.github/workflows/release-go-lib.yml@main
    with:
      version: ${{ github.ref_name }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_RELEASE }}

  build_docs:
    name: Build docs page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version-file: docs/package.json
          cache: yarn
          cache-dependency-path: docs/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: docs

      - name: Build website
        run: yarn build
        working-directory: docs

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build_docs

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
      deployments: write

    # Deploy to the Page environment
    environment:
      name: Page
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
